### ISSUE TITLE
Create one package to create themes/plugins/blocks?

### ISSUE THREAD

**Issue by ocean90** [wearerequired/js#24]
Instead of having one specific package for each boilerplate command which means copying the same code again and again, we should have only one package which combines them all. Same applies to [bugs](https://github.com/wearerequired/js/issues?q=is%3Aissue+is%3Aopen+label%3A%22%5BPackage%5D+wordpress-plugin-boilerplate%22).

For now that would be only [plugins](https://github.com/wearerequired/js/tree/master/packages/wordpress-plugin-boilerplate) and [themes](https://github.com/wearerequired/js/tree/master/packages/wordpress-theme-boilerplate) but in the future we may have one for blocks or complete WordPress setups.

This would be similar to [WP-CLI's scaffold](https://developer.wordpress.org/cli/commands/scaffold/) command. As widely known, naming stuff is hard. So, how would should we name the package/commands? Some ideas:

1. `npx @wearerequired/create plugin`, `npx @wearerequired/create theme`
   * To only replace in an existing checkout: `npx @wearerequired/create plugin --replace-only`
2. `npx @wearerequired/create wordpress-plugin` (To allow other types of plugins?)
3. `npx @wearerequired/create-wordpress plugin`, `npx @wearerequired/create-wordpress theme`, `npx @wearerequired/create-wordpress project`
4. `npx @wearerequired/init-wordpress plugin`, `npx @wearerequired/init-wordpress theme`, `npx @wearerequired/init-wordpress project`
5. `npx @wearerequired/generator wordpress-plugin`, `npx @wearerequired/generator wordpress-theme`, `npx @wearerequired/generator wordpress-project`
6. `npx @wearerequired/generator-wordpress plugin`, `npx @wearerequired/generator-wordpress theme`, `npx @wearerequired/generator-wordpress project`
7. `npx @wearerequired/generate plugin`, `npx @wearerequired/generate theme`, `npx @wearerequired/generate wordpress-project`

Any other ideas?

An alternative would be to extract [some parts of both commands into smaller packages](https://github.com/wearerequired/js/tree/master/packages/wordpress-plugin-boilerplate/lib) which then can be reused by others.

**Comment by derpaschi** [comment]
Combining the commands into one packages makes sense. I would prefer a package / command name like the following:

- `npx @wearerequired/generate wordpress-project`, `npx @wearerequired/generate wordpress-plugin`, `npx @wearerequired/generate wordpress-theme`

This could be anhanced for packages outside the WordPress environment as well. 🤷🏼

**Comment by ocean90** [comment]
The package now exists: https://github.com/wearerequired/js/tree/master/packages/generate
