### ISSUE TITLE
Use the same browserslist config for development and production

### ISSUE THREAD

**Issue by ocean90** [wearerequired/js#58]
Currently our config ships with two environments, development and production.

https://github.com/wearerequired/js/blob/bf696b10f2792ec44aa59081c843a0b391e13098/packages/browserslist-config/index.js#L2-L12

The idea was that during active development it's unlikely that we'll work with some of the older browsers. But when it comes to testing in different browsers you currently have to generate a production build first. This also means you won't notice possible issues like #35 during the development. To simplify this process I'm suggesting to remove the development environment and just use the current production environment as default.

cc: @velthy

**Comment by velthy** [comment]
👍
