### ISSUE TITLE
Command to setup staging or production environment on hosting

### ISSUE THREAD

**Issue by grappler** [wearerequired/js#71]
- [x] Collect required information
- [x] Test SSH Connection
- [x] Create `.env` file with correct database values
- [x] Create folder structure on hosting
- [x] Transfer `.env` and `.htaccess` to `shared` directory
- [ ] ~Wait for deployment~
- [ ] Run WP Install https://github.com/wearerequired/composer-deployer/pull/30

**Comment by grappler** [comment]
@derpaschi @ocean90 Habt ihr ein Vorschlag wie der Command heissen soll? `server-setup`?

**Comment by ocean90** [comment]
Du meinst Package Name? Hätte spontan `@wearerequired/setup-remote-server` gesagt, damit direkt klar ist, dass es nicht um etwas lokales geht.
