### ISSUE TITLE
404 erro for @wearerequired/generate

### ISSUE THREAD

**Issue by RiverMartinezG** [wearerequired/js#98]
After run

` npx @wearerequired/generate@latest wordpress-plugin `
the response is

`
...
 status: 404,
  response: {
    url: 'https://api.github.com/repos/wearerequired/wordpress-plugin-boilerplate/generate',
    status: 404,
    headers: {
....
`

**Comment by ocean90** [comment]
Hey there, sorry, the package is currently only intended for internal use since the boilerplate repos are still private.
